# Example Site settings

#google_analytics: UA-NNNNNNNN-N

url: "https://gs.saro.me"

header_pages:
  - list.html
  - tags.html
  - guestbook.html

# footer: '<a href="https://github.com/ac-saro">github</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

markdown: GFM

plugins:
  - jekyll-seo-tag
