# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - list.md
  - tags.md
  - guestbook.md

# footer: '<a href="https://github.com/ac-saro">github</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

markdown: GFM

plugins:
  - jekyll-seo-tag
